=== marcellodesales/myscheduler/data/myscheduler.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://cs.sfsu.edu/csc867/myscheduler" 
        xmlns:myscheduler="http://cs.sfsu.edu/csc867/myscheduler"
        elementFormDefault="qualified">

    <xsd:complexType name="UserType">
        <xsd:sequence>
            <xsd:element name="firstName" type="xsd:string" maxOccurs="1" nillable="false" />
            <xsd:element name="lastName" type="xsd:string" maxOccurs="1" nillable="false" />
            <xsd:element name="email" type="xsd:string" maxOccurs="1" nillable="true"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="username" type="xsd:string" use="required"/>
        <xsd:attribute name="password" type="xsd:string" use="required"/>

    </xsd:complexType>
    
    <xsd:complexType name="PatientType">
        <xsd:complexContent>
            <xsd:extension base="myscheduler:UserType">
                <xsd:attribute name="birthday" type="xsd:date" use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="TimeSlotType">
        <xsd:attribute name="date" type="xsd:date" use="required" />
        <xsd:attribute name="time" type="xsd:time" use="required" />
        <xsd:attribute name="duration" type="xsd:string" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="EventLocationType">
        <xsd:simpleContent>
	        <xsd:extension base="xsd:string">
	          <xsd:attribute name="zipCode" type="xsd:string" use="required"/>
	        </xsd:extension>
      </xsd:simpleContent> 
    </xsd:complexType>

    <xsd:complexType name="EventType">
        <xsd:sequence>
            <xsd:element name="timeSlot" type="myscheduler:TimeSlotType" />
            <xsd:element name="location" type="myscheduler:EventLocationType" />
            <xsd:element name="notes" type="xsd:string" maxOccurs="1" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
        <xsd:attribute name="userId" type="xsd:string" use="required" />
        <xsd:attribute name="happened" type="xsd:boolean" use="required" />
    </xsd:complexType>
    
    <xsd:complexType name="CalendarType">
        <xsd:sequence>
            <xsd:element name="event" type="myscheduler:EventType" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
        <xsd:attribute name="ownerId" type="xsd:string" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="MySchedulerType">
        <xsd:sequence>
            <xsd:element name="calendar" type="myscheduler:CalendarType" minOccurs="1" maxOccurs="unbounded" 
                        nillable="false" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="UsersListType">
        <xsd:sequence>
            <xsd:element name="user" type="myscheduler:UserType" minOccurs="1" maxOccurs="unbounded" 
                        nillable="false" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="calendars" type="myscheduler:MySchedulerType" />
    <xsd:element name="users" type="myscheduler:UsersListType" />
</xsd:schema>

=== marcellodesales/myscheduler/data/calendars.xml
<?xml version="1.0" encoding="UTF-8"?>
<myscheduler:calendars
	xmlns:myscheduler="http://cs.sfsu.edu/csc867/myscheduler"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cs.sfsu.edu/csc867/myscheduler myscheduler.xsd ">
	<myscheduler:calendar id="1208309768316" ownerId="1208309768264">
		<myscheduler:event id="1208309765755" happened="false" userId="1207537676153">
			<myscheduler:timeSlot date="2005-12-06" time="12:13:00" duration="1h" />
			<myscheduler:location zipCode="94132">
				81 Woodrow St
			</myscheduler:location>
			<myscheduler:notes>
				We have to meet at that date...
			</myscheduler:notes>
		</myscheduler:event>
		<myscheduler:event id="1208309765722"  happened="true" userId="1208309768264">
			<myscheduler:timeSlot date="2005-12-06" time="13:14:00" duration="2h" />
			<myscheduler:location zipCode="94132"></myscheduler:location>
			<myscheduler:notes>
				To review the options...
			</myscheduler:notes>
		</myscheduler:event>
		<myscheduler:event id="1208309765744"  happened="false" userId="1207537676153">
			<myscheduler:timeSlot date="2005-12-06" time="17:10:00"
				duration="5h" />
			<myscheduler:location zipCode="94132"></myscheduler:location>
			<myscheduler:notes>
				A new different topic...
			</myscheduler:notes>
		</myscheduler:event>
	</myscheduler:calendar>

</myscheduler:calendars>

=== marcellodesales/myscheduler/data/users.xml
<?xml version='1.0' encoding='UTF-8'?>
<myscheduler:users xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:myscheduler='http://cs.sfsu.edu/csc867/myscheduler' xsi:schemaLocation='http://cs.sfsu.edu/csc867/myscheduler myscheduler.xsd '>
  <myscheduler:user username='msales' password='utn29oad' id='1207535492344'>
    <myscheduler:firstName>Marcello</myscheduler:firstName>
    <myscheduler:lastName>Sales</myscheduler:lastName>
    <myscheduler:email>msales@sfsu.edu</myscheduler:email>
  </myscheduler:user>
  <myscheduler:user username='leo' password='1234' id='1207537676153'>
    <myscheduler:firstName>Leandro</myscheduler:firstName>
    <myscheduler:lastName>de Sales</myscheduler:lastName>
    <myscheduler:email>leoandroal@gmail.com</myscheduler:email>
  </myscheduler:user>
  <myscheduler:user username='thiago' password='utn29oad' id='1208309768264'>
    <myscheduler:firstName>Thiago</myscheduler:firstName>
    <myscheduler:lastName>de Sales</myscheduler:lastName>
    <myscheduler:email>thiagosales@gmail.com</myscheduler:email>
  </myscheduler:user>
</myscheduler:users>
